config/routes.rb
Rails.application.routes.draw do
  
  devise_for :views
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, controllers: { registrations: 'registrations' }
  resources :users, except: [:new, :create]
  controller :static_pages do
    get :home
    get :about
    get :contact
  end
  
  post 'static_pages/thank_you'
  post 'payments/create' => 'orders#show'

  get 'landing_page' => 'static_pages#landing_page'
  get 'featured_page' => 'static_pages#featured_page'
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'gallery' => 'static_pages#gallery'
  
  
  resources :products do 
    resources :comments
  end
  resources :payments, only: [:index, :show, :new, :create]

  root 'static_pages#index'

  resources :orders, only: [:index, :show, :new, :create]

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders
  has_many :comments
  
  def average_rating
    comments.average(:rating).to_f
  end
  validates :name, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  
  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.where("name LIKE ?", "%#{search_term}%")
    else
      @products = Product.all.paginate(page: params[:page], per_page: 5)
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.all.order("created_at DESC").paginate(page: params[:page], per_page: 3) 
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_comments.html.erb
<% cache(cache_key_for_comments) do %>
  <div class="product-reviews">
    <% @comments.each do |comment| %>
      
      <% cache(comment) do %>
        <div class="row">
          <hr>
          <ul>
            <li><%= comment.user.first_name %></li>
            <li><small><em>
              <%= "#{time_ago_in_words(comment.created_at)} ago" %>"
            </em></small>
            </li>
            <li><%= "Rating: #{comment.rating}/5" %></li>
            <li class="rated" data-score="<%= comment.rating %>"></li>
            <li class="pull-right"><% if signed_in? && current_user.admin? %>
              <%= link_to ('<span class="glyphicon glyphicon-remove"</span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you quite sure?' } %>
              <% end %>
            </li>
          </ul>
          <div><%= comment.body %></div>
        </div>
      <% end %> <!--end cache -->
    <% end %>
    <%= will_paginate @comments %>
  </div>
<% end %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
    <p>
      <%= f.label :body, "Comments" %> <br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.label :rating %> <br>
      <%= f.text_field :rating, class: "rating" %>
    </p>
    <div class="rating"></div>
    <p>
      <%= f.submit "Submit" %>
    </p>
  
  <% end %>

<% end %>

app/views/products/_product.html.erb
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>

        <td><%= image_tag product.image_url, alt: product.description, class: "product", style: "width:100px;"%></td>

        <td><%= product.colour %></td>
        <td><%= number_with_precision(product.price, precision: 2) %></td>
        <td><%= link_to 'Show', product %></td>
        <td><% if signed_in? && current_user.admin? %>
              <%= link_to 'Edit', edit_product_path(product) %>
            <% end %>
        </td>
        

      </tr>

app/views/products/edit.html.erb
<h3>Edit Product</h3>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

  <table id="products">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image</th>
      <th>Colour</th>   
      <th>Price</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @products %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Product', new_product_path %>

app/views/products/new.html.erb
<h3>New Product</h3>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-5 col-md-offset-2">
      <p id="notice"><%= notice %></p>

      <p><%= image_tag @product.image_url, alt: @product.description, class: "product" %>  </p>
    </div>
    <div class="col-md-5">   
      <p>
      <strong>Name:</strong>
        <%= @product.name %>
      </p>
      <p>
      <strong>Colour:</strong>
        <%= @product.colour %>
      </p>
      <p>
      <strong>Description:</strong>
        <%= @product.description %>
      </p>
      <p>
      <strong>Price £:</strong>
        <%= number_with_precision(@product.price, precision: 2) %>
       
      </p>
      <p>Average rating:
        <div class="rated" data-score="<%= @product.average_rating %>" ></div>
      </p>
    </div>
    
    <%= form_tag "/payments/create" do %>
      <% render partial: "shared/stripe_checkout_button" %>
    <% end %>
    <div class="col-md-10 col-md-offset-2">
      <%= render 'new_comment' %>
      
      <%= render 'comments' %>
      
      <%= link_to 'Edit', edit_product_path(@product) %> |
      <%= link_to 'Back', products_path %>
    </div>
  </div>
</div>