config/routes.rb
Rails.application.routes.draw do
  
  devise_for :views
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, controllers: { registrations: 'registrations' }
  resources :users, except: [:new, :create]
  controller :static_pages do
    get :home
    get :about
    get :contact
  end
  
  post 'static_pages/thank_you'
  post 'payments/create' => 'orders#show'

  get 'landing_page' => 'static_pages#landing_page'
  get 'featured_page' => 'static_pages#featured_page'
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'gallery' => 'static_pages#gallery'
  
  
  resources :products do 
    resources :comments
  end
  resources :payments, only: [:index, :show, :new, :create]

  root 'static_pages#index'

  resources :orders, only: [:index, :show, :new, :create]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app>
<head>
  <title>Workspace</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src='https://www.google.com/recaptcha/api.js'></script>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-fixed-top" id="nav" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <ul class="hmenu">
          <%= render 'devise/menu/registration_items' %>
          <%= render 'devise/menu/login_items' %>
        </ul>
          
        </div>
          <%= form_tag("/products", method: "get", :class => 'search pull-right') do %>
          <%= label_tag(:q, "Search for:") %>
          <%= text_field_tag(:q) %>
          <% submit_tag("Search") %>
        <% end %>
        <div class="navbar-collapse collapse" id="myScrollSpy">
          <ul class="navbar-nav nav">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'Products', products_path %></li>
            <li><%= link_to 'Orders', orders_path %></li>  
            <li><%= link_to 'Contact', contact_path %></li> 
          </ul>        
        </div><!--end navbar collapse -->
      </div><!--end navbar container-->
    </nav>
            <h1>Tots' Music Shop</h1>

      <div class="container">

        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>

        <%= yield %>
        
      </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  
</body>
</html>